name: Release package
on:
  push:
    tags:
    - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v1
      with:
        node-version: '18.7'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@ltsdev' # Defaults to the user or organization that owns the workflow file
    - run: git config --global user.name "${GITHUB_ACTOR}"
    - run: git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - run: git fetch --prune --unshallow
    - run: git checkout master
    - run: git pull    
    - run: npm version patch
    - run: git push -u origin master
    - run: npm install -g ts-node
    - run: npm run build
    - run: cd dist/npm
    - run: pwd
    - name: Authenticate with private NPM package
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > ~/.npmrc
    - run: npm publish --access restricted --tag latest
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
